// <auto-generated />
using System;
using CampChetek.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CampChetek.Migrations
{
    [DbContext(typeof(Persons))]
    [Migration("20200812195733_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CampChetek.Models.Bedding", b =>
                {
                    b.Property<string>("BeddingId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BeddingId");

                    b.ToTable("beddings");

                    b.HasData(
                        new
                        {
                            BeddingId = "A",
                            Name = "1 Queen"
                        },
                        new
                        {
                            BeddingId = "B",
                            Name = "1 Twin"
                        },
                        new
                        {
                            BeddingId = "C",
                            Name = "1 Queen, 1 Twin"
                        },
                        new
                        {
                            BeddingId = "D",
                            Name = "1 Queen, 2 Twin"
                        },
                        new
                        {
                            BeddingId = "E",
                            Name = "1 Queen, 3 Twin"
                        },
                        new
                        {
                            BeddingId = "F",
                            Name = "1 Queen, 4 Twin"
                        },
                        new
                        {
                            BeddingId = "G",
                            Name = "1 Queen, 5 Twin"
                        },
                        new
                        {
                            BeddingId = "H",
                            Name = "1 Queen, 6 Twin"
                        });
                });

            modelBuilder.Entity("CampChetek.Models.Events", b =>
                {
                    b.Property<int>("event_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BeddingId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateUpdate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberGuest")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReasonId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("RoomsId")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("Zip")
                        .HasColumnType("int");

                    b.Property<bool>("all_day")
                        .HasColumnType("bit");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("event_end")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("event_start")
                        .HasColumnType("datetime2");

                    b.Property<bool>("sendEmail")
                        .HasColumnType("bit");

                    b.Property<string>("title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("event_id");

                    b.HasIndex("BeddingId");

                    b.HasIndex("ReasonId");

                    b.HasIndex("RoomsId");

                    b.HasIndex("UserId");

                    b.ToTable("events");

                    b.HasData(
                        new
                        {
                            event_id = 1,
                            Address = "730 Lakeview Drive",
                            BeddingId = "A",
                            City = "Chetek",
                            Email = "pr@campchetek.org",
                            FirstName = "Randy",
                            LastName = "Tanis",
                            Message = "",
                            NumberGuest = 2,
                            Phone = "715 924-3236",
                            ReasonId = "J",
                            RoomsId = 30,
                            State = "WI",
                            UserId = 1,
                            Zip = 54728,
                            all_day = false,
                            description = "test ",
                            event_end = new DateTime(2020, 8, 12, 0, 0, 0, 0, DateTimeKind.Local),
                            event_start = new DateTime(2020, 8, 12, 14, 57, 32, 492, DateTimeKind.Local).AddTicks(9935),
                            sendEmail = false,
                            title = "Test "
                        },
                        new
                        {
                            event_id = 2,
                            Address = "730 Lakeview Drive",
                            BeddingId = "B",
                            City = "Chetek",
                            Email = "noah@campchetek.org",
                            FirstName = "Noah",
                            LastName = "Rost",
                            Message = "",
                            NumberGuest = 1,
                            Phone = "715 924-3236",
                            ReasonId = "J",
                            RoomsId = 30,
                            State = "WI",
                            UserId = 2,
                            Zip = 54728,
                            all_day = false,
                            description = "test2 ",
                            event_end = new DateTime(2020, 8, 12, 0, 0, 0, 0, DateTimeKind.Local),
                            event_start = new DateTime(2020, 8, 12, 14, 57, 32, 499, DateTimeKind.Local).AddTicks(862),
                            sendEmail = false,
                            title = "Test2 "
                        });
                });

            modelBuilder.Entity("CampChetek.Models.Reason", b =>
                {
                    b.Property<string>("ReasonId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReasonId");

                    b.ToTable("Reasons");

                    b.HasData(
                        new
                        {
                            ReasonId = "A",
                            Name = "Pastor"
                        },
                        new
                        {
                            ReasonId = "B",
                            Name = "Missionary"
                        },
                        new
                        {
                            ReasonId = "C",
                            Name = "Evanglist"
                        },
                        new
                        {
                            ReasonId = "D",
                            Name = "Former Staff"
                        },
                        new
                        {
                            ReasonId = "E",
                            Name = "Former Camper"
                        },
                        new
                        {
                            ReasonId = "F",
                            Name = "Rental"
                        },
                        new
                        {
                            ReasonId = "G",
                            Name = "Family Of Staff"
                        },
                        new
                        {
                            ReasonId = "H",
                            Name = "Sponsor"
                        },
                        new
                        {
                            ReasonId = "I",
                            Name = "Attending An Event"
                        },
                        new
                        {
                            ReasonId = "J",
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("CampChetek.Models.Rooms", b =>
                {
                    b.Property<int>("RoomsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("RoomsId");

                    b.HasIndex("StatusId");

                    b.ToTable("Room");

                    b.HasData(
                        new
                        {
                            RoomsId = 1,
                            Name = "Schnick 1",
                            StatusId = "D"
                        },
                        new
                        {
                            RoomsId = 2,
                            Name = "Schnick 2",
                            StatusId = "D"
                        },
                        new
                        {
                            RoomsId = 3,
                            Name = "Schnick 3",
                            StatusId = "D"
                        },
                        new
                        {
                            RoomsId = 4,
                            Name = "Schnick 4",
                            StatusId = "D"
                        },
                        new
                        {
                            RoomsId = 5,
                            Name = "Tomah 1",
                            StatusId = "D"
                        },
                        new
                        {
                            RoomsId = 6,
                            Name = "Tomah 2",
                            StatusId = "D"
                        },
                        new
                        {
                            RoomsId = 7,
                            Name = "Tomah 3",
                            StatusId = "D"
                        },
                        new
                        {
                            RoomsId = 8,
                            Name = "Tomah 4",
                            StatusId = "D"
                        },
                        new
                        {
                            RoomsId = 9,
                            Name = "New Lisbon 1",
                            StatusId = "D"
                        },
                        new
                        {
                            RoomsId = 10,
                            Name = "New Lisbon 2",
                            StatusId = "D"
                        },
                        new
                        {
                            RoomsId = 11,
                            Name = "Chetek",
                            StatusId = "D"
                        },
                        new
                        {
                            RoomsId = 12,
                            Name = "RV Park",
                            StatusId = "D"
                        },
                        new
                        {
                            RoomsId = 13,
                            Name = "Sanasac 1",
                            StatusId = "D"
                        },
                        new
                        {
                            RoomsId = 14,
                            Name = "Sanasac 2",
                            StatusId = "D"
                        },
                        new
                        {
                            RoomsId = 15,
                            Name = "Sanasac 3",
                            StatusId = "D"
                        },
                        new
                        {
                            RoomsId = 16,
                            Name = "Sanasac 4",
                            StatusId = "D"
                        },
                        new
                        {
                            RoomsId = 17,
                            Name = "Dining Hall 1",
                            StatusId = "D"
                        },
                        new
                        {
                            RoomsId = 18,
                            Name = "Dining Hall 2",
                            StatusId = "D"
                        },
                        new
                        {
                            RoomsId = 19,
                            Name = "Dining Hall 3",
                            StatusId = "D"
                        },
                        new
                        {
                            RoomsId = 20,
                            Name = "Dining Hall 4",
                            StatusId = "D"
                        },
                        new
                        {
                            RoomsId = 21,
                            Name = "Dining Hall 5",
                            StatusId = "D"
                        },
                        new
                        {
                            RoomsId = 22,
                            Name = "Hotel 1",
                            StatusId = "D"
                        },
                        new
                        {
                            RoomsId = 23,
                            Name = "Hotel 2",
                            StatusId = "D"
                        },
                        new
                        {
                            RoomsId = 24,
                            Name = "Hotel 3",
                            StatusId = "D"
                        },
                        new
                        {
                            RoomsId = 25,
                            Name = "Hotel 4",
                            StatusId = "D"
                        },
                        new
                        {
                            RoomsId = 26,
                            Name = "Hotel 5",
                            StatusId = "D"
                        },
                        new
                        {
                            RoomsId = 27,
                            Name = "Hotel 6",
                            StatusId = "D"
                        },
                        new
                        {
                            RoomsId = 28,
                            Name = "Hotel 7",
                            StatusId = "D"
                        },
                        new
                        {
                            RoomsId = 29,
                            Name = "Hotel 8",
                            StatusId = "D"
                        },
                        new
                        {
                            RoomsId = 30,
                            Name = "None",
                            StatusId = "D"
                        });
                });

            modelBuilder.Entity("CampChetek.Models.Status", b =>
                {
                    b.Property<string>("StatusId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StatusId");

                    b.ToTable("Statuses");

                    b.HasData(
                        new
                        {
                            StatusId = "C",
                            Name = "Clean"
                        },
                        new
                        {
                            StatusId = "D",
                            Name = "Dirty"
                        },
                        new
                        {
                            StatusId = "O",
                            Name = "Occupied"
                        },
                        new
                        {
                            StatusId = "R",
                            Name = "Ready"
                        });
                });

            modelBuilder.Entity("CampChetek.Models.User", b =>
                {
                    b.Property<int>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.Property<bool>("RememberMe")
                        .HasColumnType("bit");

                    b.Property<string>("ReturnUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserPassword")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("userId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            userId = 1,
                            Email = "danael@campchetek.org",
                            FirstName = "Dan",
                            LastName = "Kluver",
                            Password = "cccc1944ad",
                            RememberMe = false
                        },
                        new
                        {
                            userId = 2,
                            Email = "marikkakay@yahoo.com",
                            FirstName = "Marikka",
                            LastName = "Kartman",
                            Password = "Marikka0410",
                            RememberMe = false
                        },
                        new
                        {
                            userId = 3,
                            Email = "system@campchetek.org",
                            FirstName = "System",
                            LastName = "1",
                            Password = "12Ers45Bd5sS@",
                            RememberMe = false
                        },
                        new
                        {
                            userId = 4,
                            Email = "pr@campchetek.org",
                            FirstName = "Randy",
                            LastName = "Tanis",
                            Password = "Pronly3236",
                            RememberMe = false
                        },
                        new
                        {
                            userId = 5,
                            Email = "email@goeshere.org",
                            FirstName = "First",
                            LastName = "Last",
                            Password = "X234Veeetw123",
                            RememberMe = false
                        });
                });

            modelBuilder.Entity("CampChetek.Models.Events", b =>
                {
                    b.HasOne("CampChetek.Models.Bedding", "Bedding")
                        .WithMany()
                        .HasForeignKey("BeddingId");

                    b.HasOne("CampChetek.Models.Reason", "Reason")
                        .WithMany()
                        .HasForeignKey("ReasonId");

                    b.HasOne("CampChetek.Models.Rooms", "Rooms")
                        .WithMany()
                        .HasForeignKey("RoomsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CampChetek.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CampChetek.Models.Rooms", b =>
                {
                    b.HasOne("CampChetek.Models.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId");
                });
#pragma warning restore 612, 618
        }
    }
}
